### PR TITLE
Add covariance matrix computation + ellipse drawing for graphSLAM.

### PR DESCRIPTION
**Pull request by marija-p**
Hey @joansola , here's my PR. I tested it and it seems to work for me with the standard example. Please let me know if I should make any changes. Many thanks for the opportunity to contribute! :smile:  Masha

### CODE REVIEW

**Comment by joansola** [comment]
OK Merged! You are now in the credits, congratulations!!

Joan

**Comment by marija-p** [comment]
@joansola Thanks a lot! :+1: Could you please change my name to "Marija"? :smile: Not "Marjia"?

**Comment by joansola** [comment]
Oh !! Of course, and sorry!

J

**Comment by marija-p** [comment]
@joansola Thanks :)

**Pull request merged**
